spring:
  resources:
    static-locations:
    - classpath:static/
    - file:static/
  mvc:
    static-path-pattern: /**
  datasource:
    username: root
    password: Zhurui@111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC
    initialization-mode: always
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  

